AllCops:
  NewCops: enable
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/MethodLength:
  Max: 40
Metrics/PerceivedComplexity:
  Description:
    A complexity metric geared towards measuring complexity for a human
    reader.
  Enabled: false
  Max: 7
